---
title: "Dashboard Ações"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup_libraries, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(plotly)
library(tidyquant)
```
Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput(
  "ticker",
  "Escolha o ticket:",
  choices= c("PETR4.SA","BBAS3.SA","VALE3.SA","WEGE3.SA")
)
```

```{r download }
dados_tbl <- reactive({
  tq_get(input$ticker)
})
```

Column {data-width=500}
-----------------------------------------------------------------------
```{r table}
renderDataTable({
dados_tbl()%>%
  select(date,adjusted) %>%
  arrange(desc(date))
})
```

Column {data-width=500}
-----------------------------------------------------------------------
```{r Grafico de linha}
renderPlotly(
  dados_tbl()%>%
  ggplot(aes(x=date,y=adjusted)) +
  geom_line()
)
```
-----------------------------------------------------------------------
```{r}
renderPlotly(
  tq_get(c("PETR4.SA","BBAS3.SA","VALE3.SA","WEGE3.SA")) %>% 
  group_by(symbol) %>% 
  mutate(cotacao = (adjusted - mean(adjusted))/ sd( adjusted)) %>% 
  ungroup() %>%  
  ggplot(aes(x=date,y=cotacao, color = symbol)) +
  geom_line()
)
```